# Generated by Django 2.1.2 on 2019-01-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20190102_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='studentid',
            new_name='student',
        ),
        migrations.AddField(
            model_name='commission',
            name='studentidd',
            field=models.CharField(db_column='ÖiD', default=1, max_length=6, verbose_name='Öğrenci no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='studentid',
            field=models.CharField(db_column='ÖiD', default=1, max_length=6, verbose_name='Öğrenci no'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='currentday',
            field=models.PositiveIntegerField(db_column='GGÜN', default=1, verbose_name='Geçerli gün'),
            preserve_default=False,
        ),
    ]
